# SwiftLint Configuration for INDIKit

# Rules to enable/disable
disabled_rules:
  - todo # Allow TODO comments
  - trailing_whitespace # Let formatter handle this

# Rules to opt-in
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Paths to ignore
excluded:
  - .build
  - .swiftpm
  - Docs
  - Tests

# Line length
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Type body length
type_body_length:
  warning: 300
  error: 400

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Force casting
force_cast: warning
force_try: warning

# Identifier names
identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - x
    - y
    - z

# Type name
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"

